# Generated by Django 2.2.17 on 2020-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="HGjdthe5t6hre67uj5jurytghbv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdgwr", models.BigIntegerField()),
            ],
        ),
    ]
